### ISSUE TITLE
Milestone 3

### ISSUE THREAD

**Issue by daanish764** [FrankSauve/345BudgetApp#14]
The application ought to run on a the new mySQL database in the same way it runs on the current Postgres database, and with consistency. 

The migration task can be broken down into following sub tasks:

- [x] Write a forklift to move over old data to new data (**daanish93**) + (**FrankSauve**)#16 
- [x] Write a consistency checker that ensures that old data is consistent with new data (**LeCleric**) #17 
- [x] Shadow Writes #18 (**daanish93**)
- [x] Shadow Reads for Validation #19 (**williamkingbede**)
- [x] Read and write from the new datastore (**Raph1105**) #20 
- [ ] Long-term consistency checker #21

**Comment by daanish764** [comment]
the previous commit handles the error to overwritting data 

![image](https://user-images.githubusercontent.com/35245868/38159688-c292c730-347b-11e8-9dea-41f03ba915a3.png)

If the data already exits then we need to catch the error and handle it. ccd0f42b8ac86d318cac4fae3f219b87761f3d43

**Comment by daanish764** [comment]
Tested and works. 

![image](https://user-images.githubusercontent.com/35245868/38159799-39b0bc58-347e-11e8-9bba-c81621480261.png)

#15  Merged it with master.

**Comment by FrankSauve** [comment]
Forklifts are done 
#16 is closed

**Comment by FrankSauve** [comment]
Consistency checker is done.
#17 is closed

**Comment by daanish764** [comment]
Shadow Writing is done.
#18 is closed.
